### ISSUE TITLE
Hola! Cuidado

### ISSUE THREAD

**Issue by klap50** [ingadhoc/ansible_notebooks#1]
Hola en el YML encontre esto:
    # mkpasswd --method=sha-512
    password: "$6$aa23AZ33HPpuMtWN$prqZecPTgNnxnh25.5YZ.a4y10fMnYTeUkGhxFy4M3ROp3W2fzEB32YSbzM8Lx0zIJVbIIOsc7VU8CUGvJvN9/"
    
   no es una buena practica, aunq este encriptado. como diria un amigo NO HARDCODES PASSW en CODIGOS! jajaja
saludos!

**Comment by az-adhoc** [comment]
Hey, Gracias por el reporte y disculpa la demora por responder! Es un placeholder :-) pero muy atento de tu parte. gracias.

**Comment by klap50** [comment]
de nada!
